version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: messagepunk-redis
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data  
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: messagepunk-rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user  
      RABBITMQ_DEFAULT_PASS: password
      RABBIMQ_HOSTNAME: rabbitmq  
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: messagepunk-postgres
    ports:
      - "5432:5432"  
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data  
    networks:
      - app-network

volumes:
  redis_data:
  rabbitmq_data:
  pg_data:

networks:
  app-network:
    external: true
    driver: bridge  
