name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Debug Secrets
        env:
            CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
            CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        run: |
            echo "Publishable Key set: ${CLERK_PUBLISHABLE_KEY:?Not set}"
            echo "Secret Key set: ${CLERK_SECRET_KEY:?Not set}"
            echo "Publishable Key length: ${#CLERK_PUBLISHABLE_KEY}"
            echo "Secret Key length: ${#CLERK_SECRET_KEY}"

      - name: Install dependencies
        run: npm install

      - name: Run setup script
        run: npm run setup
    
      - name: Verbose Clerk Debug
        run: |
          echo "Checking Clerk keys"
          echo "Publishable Key length: ${#CLERK_PUBLISHABLE_KEY}"
          echo "Secret Key length: ${#CLERK_SECRET_KEY}"

      - name: Build
        env:
          CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          CLERK_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}
        run: npm run build
